---
title: "About this site"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## About me

My name is **Sai Gottemukkula**, and I'm currently a rising junior at Lexington High School. I enjoy learning about tech, as well as biking with my friends, and playing tennis whenever I can.

## About the project

I chose to do a project based on the Coronavirus pandemic because it was a global event that completely changed the lives of the current generation, affecting everything from education to jobs. I also felt like I would have done a disservice to all the people that it affected if I did not select the pandemic as my topic.

## Contact links
* E-mail: saigthefirst@gmail.com
* Github: https://github.com/SaiGottemukkula
* Github repo for this site: https://github.com/SaiGottemukkula/AnExplorationOfCOVID-19.git

## Credits
I made this website as a final project for [David Kane's free datascience bootcamp](https://bootcamp.davidkane.info/)! Feel free to check it out - the bootcamp is very informative!

