---
title: "Coronavirus Deaths vs Cases"
description: |
  [Insert DESCRIPTION Here].
author:
  - name: Sai Gottemukkula
    
date: "`r Sys.Date()`"
output: distill::distill_article
bibliography: bibliography.bib

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(rvest)
library(ggthemes)
library(janitor)
library(dplyr)
```

```{r graph, echo = FALSE}
table <- read_csv(file = "United_States_COVID-19_Cases_and_Deaths_by_State_over_Time.csv", show_col_types = FALSE)
```

```{r conversion, echo = FALSE}
#colnames(table) = c("submission_date", "state", "tot_cases", "ChangeInTotalPercent")

table$tot_death <- as.numeric(table$tot_death)
table$tot_cases <- as.numeric(table$tot_cases)
```

```{r graphing, echo = FALSE}
table |>
  select(tot_cases, tot_death) |>
  ggplot(aes(x = tot_cases, y = tot_death)) +
  geom_point(size = 0.15) + 
  geom_smooth() +
  labs(title = "Coronavirus Cases To Deaths Ratio", subtitle = "The ratio continued upwards for most of the pandemic", x = "Coronavirus Cases", y = "Coronavirus Deaths", caption = "Source: CDC")
```

[@Source1]